---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access
subjects:
- kind: ServiceAccount
  name: access
  namespace: default
roleRef:
  kind: ClusterRole
  name: access
  apiGroup: rbac.authorization.k8s.io